### PR TITLE
Add requirement for AAD account connected to Windows

### PR DESCRIPTION
**Pull request by apmpinho**
As we continue to receive customers cases where this basic requirement is not fulfilled.

### CODE REVIEW

**Comment by apmpinho** [comment]
@dan-wesley can you provide an ETA on this one, please? Thank you.

**Comment by apmpinho** [comment]
@dan-wesley, will this ever get approved/rejected?

**Comment by dan-wesley** [comment]
@apmpinho reviewed, approved, and merged

**Comment by apmpinho** [comment]
Thank you Dan

**Pull request merged**
