### PR TITLE
Update edge-ie-mode-faq.md

### PR DESCRIPTION
**Pull request by HeikoMayer**
Adding additional info about saving pages in IE-Mode

### CODE REVIEW

**Review by dan-wesley — COMMENTED** [review]
Thank you for providing this information. We'll run in by someone on the product team for review /approval.

**Review by dan-wesley — COMMENTED** [review]
Some minor edits then we can merge this.

254 first sentence, change "Internet Explorer mode" to "Internet Explorer (IE) mode"
254 path format
**Computer Configuration** > **Administrative Templates** > **Windows Components** > **Internet Explorer**.
256 IE-Mode should be IE mode
262 use same path format as 254
263 typos
The ability to use the "Save page as" menuitem requires

**Comment by dan-wesley** [comment]
@HeikoMayer I can merge this after you make the changes that I called out in my review last week

**Comment by HeikoMayer** [comment]
@dan-wesley please let me know if this works better. thx, Heiko

**Review by dan-wesley — APPROVED** [review]

**Comment by dan-wesley** [comment]
@HeikoMayer approved the changes and did the merge

**Pull request merged**
