### PR TITLE
IE Mode: Add reference to test mode

### PR DESCRIPTION
**Pull request by fowl2**

### CODE REVIEW

**Comment by AndreaLBarr** [comment]
@fowl2  Is this still needed or did Dan get this added for you?

**Comment by fowl2** [comment]
Perhaps a typo in the commit message? as that doesn't look related

**Comment by AndreaLBarr** [comment]
@fowl2  Does this pr need any work then or can it be closed?

**Comment by fowl2** [comment]
I think it'd still be valuable to merge it

**Pull request merged**
